### ISSUE TITLE
指定したprojectに参加、リダイレクトされない

### ISSUE THREAD

**Issue by ShiraiChisato** [ShiraiChisato/TaskShareApp#13]
```rb:app>controllers>project_controller.rb
  def join
    @project = Project.find(params[:id])
    puts "----------------------------------"
    puts params[:id]
    if @project.users.pluck(:id).include?(current_user.id)
      flash[:notice] = "既に加入しています"
      redirect_to @project
    else
      @project.users << current_user
      redirect_to @project
    end
  end
```
```erb
 <div class = "button">
    <%= button_to "参加", join_project_path(project), method: :post %>
 </div>
```

コンソールの挙動
```bash
Started POST "/projects/2/join" for ::1 at 2021-09-25 16:21:23 +0900
Processing by ProjectsController#join as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "id"=>"2"}
  Project Load (1.1ms)  SELECT `projects`.* FROM `projects` WHERE (2) LIMIT 1
  ↳ app/controllers/projects_controller.rb:65:in `join'
----------------------------------
2    #project.id
   (1.0ms)  SELECT `users`.`id` FROM `users` INNER JOIN `associates` ON `users`.`id` = `associates`.`user_id` WHERE `associates`.`project_id` = 1
  ↳ app/controllers/projects_controller.rb:68:in `join'
  User Load (1.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 ORDER BY `users`.`id` ASC LIMIT 1
  ↳ app/controllers/projects_controller.rb:68:in `join'
Redirected to http://localhost:3000/projects/1
Completed 302 Found in 9ms (ActiveRecord: 3.2ms | Allocations: 3540)
```

**Comment by raisa0726** [comment]
# 解決策

```rb

  def join
    @project = Project.find(params[:id])
    puts "----------------------------------"
    puts params[:id]
    if @project.users.pluck(:id).include?(current_user.id)
      flash[:notice] = "既に加入しています"
      redirect_to @project
    else
      @project.users << current_user
      redirect_to @project
    end
  end
```
## 反省点
find_by で取得してはいけなかった。
